volumes:
  jdbcVOL:

services:
  sportDataDB:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=sportDataDB
    volumes:
      - jdbcVOL:/var/lib/postgresql/data

    ports:
      - "127.0.0.1:5433:5432"
